# Generated by Django 3.1 on 2020-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.DateTimeField()),
            ],
        ),
    ]
